name: Run Smoke Tests on Deploy

on:
  push:
    branches:
#      - 'main'
      - 'feature/run-smoke-tests-on-deploy'

env:
  JWKS_URL: http://localhost:9229/local_6GLuhxhD/.well-known/jwks.json

jobs:
  run-sag-smoke-tests:
    runs-on: ubuntu-latest

    services:
      cognito-local:
        image: jagregory/cognito-local:latest
        ports:
          - 9229:9229

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Ping cognito-local
        run: |
          curl http://localhost:9229

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
          cache-dependency-path: 'pom.xml'
#          server-id: github
#          server-username: ${{ github.actor }}
#          server-password: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Maven settings
        run: |
          mkdir -p ~/.m2
          echo "<settings><servers><server><id>github</id><username>${{ github.actor }}</username><password>${{ secrets.GH_PACKAGES_PAT }}</password></server></servers></settings>" > ~/.m2/settings.xml

      - name: Build secure-agent-graph
        run: mvn clean install --batch-mode --no-transfer-progress -Dgpg.skip=true

#      - name: Setup cognito
#        run:
#          |

      - name: Run secure-agent-graph Smoke Tests
        run: |
          cd sag-docker/Test
          ./smoke-test-local.sh

