name: Run Smoke Tests on Deploy

on:
  push:
    branches:
#      - 'main'
      - 'feature/run-smoke-tests-on-deploy'

env:
  AWS_REGION: eu-west-2
  AWS_ACCESS_KEY_ID: smoke-test
  AWS_SECRET_ACCESS_KEY: smoke-test
  JWKS_URL: http://localhost:9229/local_6GLuhxhD/.well-known/jwks.json
  HURL_VERSION: 6.1.1

jobs:
  run-sag-smoke-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Cognito Local
        run: |
          docker run -d --name cognito-local-ndtp \
            -v ./sag-docker/Test/cognito-local:/app/.cognito \
            -p 9229:9229 \
            jagregory/cognito-local:latest

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
          cache-dependency-path: 'pom.xml'

      - name: Configure Maven settings
        run: |
          mkdir -p ~/.m2
          echo "<settings><servers><server><id>github</id><username>${{ github.actor }}</username><password>${{ secrets.GH_PACKAGES_PAT }}</password></server></servers></settings>" > ~/.m2/settings.xml

      - name: Build secure-agent-graph
        run: mvn clean install --batch-mode --no-transfer-progress -Dgpg.skip=true

      - name: Ping cognito-local
        run: |
          curl http://localhost:9229

      - name: Configure Cognito Local
        run: |
          aws --endpoint http://0.0.0.0:9229 cognito-idp admin-create-user --user-pool-id local_6GLuhxhD --username test+user@ndtp.co.uk --cli-read-timeout 0 --message-action SUPPRESS --user-attributes Name=email,Value=test+user@ndtp.co.uk
          aws --endpoint http://0.0.0.0:9229 cognito-idp admin-create-user --user-pool-id local_6GLuhxhD --username test+user+admin@ndtp.co.uk --cli-read-timeout 0 --message-action SUPPRESS --user-attributes Name=email,Value=test+user+admin@ndtp.co.uk
          
          aws --endpoint http://0.0.0.0:9229 cognito-idp admin-set-user-password --user-pool-id local_6GLuhxhD --username test+user+admin@ndtp.co.uk --password password --permanent
          aws --endpoint http://0.0.0.0:9229 cognito-idp admin-set-user-password --user-pool-id local_6GLuhxhD --username test+user@ndtp.co.uk --password password --permanent
          
          aws --endpoint http://0.0.0.0:9229 cognito-idp create-group --user-pool-id local_6GLuhxhD  --group-name ianode_admin
          aws --endpoint http://0.0.0.0:9229 cognito-idp create-group --user-pool-id local_6GLuhxhD  --group-name ianode_read
          
          aws --endpoint http://0.0.0.0:9229 cognito-idp admin-add-user-to-group --user-pool-id local_6GLuhxhD --username test+user@ndtp.co.uk --group-name ianode_read
          aws --endpoint http://0.0.0.0:9229 cognito-idp admin-add-user-to-group --user-pool-id local_6GLuhxhD --username test+user+admin@ndtp.co.uk --group-name ianode_admin
          aws --endpoint http://0.0.0.0:9229 cognito-idp admin-add-user-to-group --user-pool-id local_6GLuhxhD --username test+user+admin@ndtp.co.uk --group-name ianode_read

#      - name: (debug) Start SAG outside the smoke test
#        run: |
#          java \
#          -classpath "sag-server/target/classes:sag-system/target/classes:sag-docker/target/dependency/*" \
#          uk.gov.dbt.ndtp.secure.agent.graph.SecureAgentGraph \
#          --config sag-docker/mnt/config/dev-server-graphql.ttl &
#
#      - name: (debug) Send data to SAG
#        run: |
#          ID_TOKEN=$(aws --endpoint http://0.0.0.0:9229 cognito-idp initiate-auth --client-id 6967e8jkb0oqcm9brjkrbcrhj --auth-flow USER_PASSWORD_AUTH --auth-parameters USERNAME=$USER_1,PASSWORD=password | jq -r '.AuthenticationResult.IdToken')
#          curl -XPOST -T ./sag-docker/Test/data1.trig --header "Content-type: text/trig" -H "Authorization: bearer $ID_TOKEN" http://localhost:3030/ds/upload

      - name: Download Smoke Test Dependencies
        run: |
          sudo apt-add-repository -y ppa:lepapareil/hurl 
          sudo apt install hurl="${{ env.HURL_VERSION }}"*
          sudo apt-get install jq

      - name: Run secure-agent-graph Smoke Tests
        run: |
          cd sag-docker/Test
          ./smoke-test-local.sh

